### ISSUE TITLE
extended TODO

### ISSUE THREAD

**Issue by yaruwangway** [interchainberlin/slackbot#25]
- [ ]  write ourown mnemonic generator
- [ ] rewrite` init.sh`: no need to re-init the state for every test case (save the time for initializing pooltoy), no dependency on other files.
- [ ] check cofirmUser errorout.
